# 哨兵
KE0200110075:
    #陀螺仪坐标系：枪口反方向为x轴正向，弹舱舵机右侧为y轴正向，垂直向上为z轴正向
    #内参矩阵
    Intrinsic:  [1675.042871,  0.000000000000,  623.481121,
                0.000000000000,1674.696037, 556.002821,
                0.000000000000,  0.000000000000,  1.000000000000]
    Coeff: [-0.06719080320827164, 0.08771589756714641, 0.0, 0.0009056377800116876, -0.004604447207374161] 
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,0,0]
    #yaw,pitch角度偏移量,单位度 left- down-
    angle_offset: [0,0]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci:  [-0.00687597 , 0.9999657 ,  0.0046184  , 0.00935481,
            0.0005452  , 0.00462226, -0.99998917 , 0.00111573,
            -0.99997621 ,-0.00687337, -0.00057697 ,-0.00203505,
            0         , 0        ,  0         , 1.        ]
    #相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [-0.00687597,  0.0005452 , -0.99997621, -0.00197128,
            0.9999657 ,  0.00462226, -0.00687337, -0.00937364,
            0.0046184 , -0.99998917, -0.00057697, 0.00107134,
            0         ,  0         , 0          ,  1.        ]
    #陀螺仪至云台转轴中心平移向量 R_g = R_i - T_iw
    T_iw: [-0.1, 0, -0.05]

# 英雄
KE0200110073:
    #内参矩阵
    Intrinsic: [1725.78369, 0.00000000, 643.24625,
                0.00000000, 1727.74255, 521.50776,
                0.00000000, 0.00000000, 1.0000000]
    #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
    Coeff: [-0.079929, 0.398026, 0.0, 0.000968, -0.000006]
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,0,0]
    #yaw,pitch角度偏移量,单位度
    angle_offset: [-1.65, -2.65]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci: [0.07629603,  0.99707592,  -0.0043046,  -0.02099209,
           0.02154182,  -0.00596452, -0.99975016, 0.04293658,
           -0.99685248, 0.07618424,  -0.0219339,  -0.00308126,
           0.,          0.,          0.,          1.         ]
    #相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [0.07629603, 0.02154182,  -0.99685248, -0.00239488,
           0.99707592, -0.00596452, 0.07618424,  0.02142155,
           -0.0043046, -0.99975016, -0.0219339,  0.04276791,
           0.,         0.,          0.,          1.        ]
    #陀螺仪至云台转轴中心平移向量 R_w = R_i - T_iw
    T_iw: [0.02, 0.01, -0.05]
   
# 3号步兵
KE0200110074:
    #内参矩阵
    Intrinsic:  [1289.699097, 0.000000, 636.757080,
                 0.000000, 1289.549067, 459.640587,
                0.000000000000,  0.000000000000,  1.000000000000]
    #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
    Coeff: [-0.181445, 0.162407, 0, -0.008906, 0.002060]
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0,0,0]
    #yaw,pitch角度偏移量,单位度
    angle_offset: [0, 3]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    
    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci:  [-0.99996235, -0.00031556, -0.00867201,  0.06587003,
        0.00866912, -0.0808866,  -0.99668561,  0.110437,  
        -0.00038694, -0.99672326,  0.08088629, -0.33649534,
        0.,          0.,          0.,          1.        ]
    #相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [-0.99996235,  0.00866912,  -0.00038694, 0.06587003,
        -0.00031556, -0.0808866, -0.99672326, -0.33649534,
        -0.00867201,   -0.99668561,  0.08088629, 0.110437,
        0         , 0        ,  0         , 1.  ]
    #陀螺仪至云台转轴中心平移向量 R_w = R_i - T_iw
    T_iw: [0, 0, 0]

# 5号blancer步兵
KE0200110076:
    #内参矩阵
    Intrinsic: [1656.55423,  0.000000000000,  691.49622,
                0.000000000000, 1659.44139, 482.0145,
                0.000000000000,  0.000000000000,  1.000000000000]
    #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
    Coeff: [-0.083215, 0.179504, 0.0, -0.001395,  0.004738]
    #x,y,z坐标偏移量(相机至枪管),单位m
    xyz_offset: [0, 0, 0]
    #yaw,pitch角度偏移量,单位度
    angle_offset: [2.01, 1.45]
    #使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    #停止迭代的最小误差(单位m)
    stop_error: 0.001
    #龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    #陀螺仪到相机的变换矩阵 R_c = T_ci * R_i
    T_ci: [-0.015054, -0.99745114, -0.06974674 ,0.00272642,
           -0.02372202, 0.07009129, -0.99725848, 0.00051117,
            0.99960524, -0.0133582, -0.02471671, 0.00006743,
            0,          0,              0,      1.      ]
    #相机到陀螺仪的变换矩阵 R_i = T_ic * R_c
    T_ic: [-0.015054, -0.02372202, 0.99960524, -0.00001424,
           -0.99745114, 0.07009129, -0.0133582, 0.00268454,
           -0.06974674, -0.99725848, -0.02471671, 0.0007016, 
            0,           0,              0,      1.     ]
    #陀螺仪至云台转轴中心平移向量 R_w = R_i - T_iw
    T_iw: [0.02, -0.02, -0.02]